
###############################
# Victory points distribution #
###############################

province = { id = 9 points = 5 } # Glasgow
province = { id = 10 points = 5 } # Edinburgh
province = { id = 11 points = 10 } # Sunderland
province = { id = 16 points = 5 } # Birmingham
province = { id = 19 points = 30 } # London
province = { id = 28 points = 5 } # Belfast
province = { id = 30 points = 2 } # Dublin
province = { id = 31 points = 3 } # Malta
province = { id = 39 points = 5 } # Caen
province = { id = 41 points = 1 } # Le Havre
province = { id = 43 points = 2 } # Dunkerque
province = { id = 44 points = 2 } # Lille
province = { id = 47 points = 5 } # Amsterdam
province = { id = 50 points = 2 } # Antwerp
province = { id = 51 points = 3 } # Brussels
province = { id = 56 points = 25 } # Paris
province = { id = 67 points = 25 } # Essen
province = { id = 71 points = 1 } # Luxembourg
province = { id = 73 points = 2 } # Strasbourg
province = { id = 75 points = 10 } # Cologne
province = { id = 84 points = 5 } # Erfurt
province = { id = 86 points = 5 } # Hannover
province = { id = 88 points = 5 } # Hamburg
province = { id = 90 points = 5 } # Kiel
province = { id = 92 points = 1 } # Århus
province = { id = 93 points = 1 } # Malmö
province = { id = 98 points = 2 } # Göteborg
province = { id = 101 points = 4 } # Stockholm
province = { id = 105 points = 1 } # Karlstad
province = { id = 107 points = 5 } # Oslo
province = { id = 113 points = 1 } # Falun
province = { id = 125 points = 1 } 
province = { id = 133 points = 5 } # Murmansk
province = { id = 138 points = 1 } # Vaasa
province = { id = 141 points = 1 } # Turku
province = { id = 142 points = 3 } # Helsinki
province = { id = 145 points = 1 } # Viipuri
province = { id = 154 points = 5 } # Archangelsk
province = { id = 163 points = 30 } # Stalingrad
province = { id = 174 points = 2 } # Kalinin
province = { id = 175 points = 50 } # Moscow
province = { id = 187 points = 30 } # Leningrad
province = { id = 194 points = 2 } # Tallinn
province = { id = 197 points = 2 } # Riga
province = { id = 207 points = 2 } # Kaunas
province = { id = 209 points = 2 } # Grodno
province = { id = 212 points = 5 } # Minsk
province = { id = 217 points = 2 } # Vitebsk
province = { id = 219 points = 5 } # Smolensk
province = { id = 233 points = 2 } # Odessa
province = { id = 238 points = 5 } # Kiev
province = { id = 248 points = 2 } # Kharkov
province = { id = 253 points = 2 } # Sevastopol
province = { id = 258 points = 2 } # Rostov
province = { id = 293 points = 1 } # Odense
province = { id = 294 points = 1 } # Copenhagen
province = { id = 300 points = 30 } # Berlin
province = { id = 303 points = 2 } # Danzig
province = { id = 310 points = 5 } # Leipzig
province = { id = 311 points = 5 } # Dresden
province = { id = 312 points = 5 } # Nuremberg
province = { id = 314 points = 5 } # Stuttgart
province = { id = 316 points = 7 } # Mulhouse
province = { id = 320 points = 5 } # Vichy
province = { id = 325 points = 7 } # Bordeaux
province = { id = 331 points = 2 } # Bilbao
province = { id = 333 points = 1 } # Burgos
province = { id = 334 points = 1 } # La Coruña
province = { id = 335 points = 1 } # Oporto
province = { id = 336 points = 3 } # Lissabon
province = { id = 339 points = 1 } # Valladolid
province = { id = 341 points = 3 } # Madrid
province = { id = 342 points = 1 } # Guadalajara
province = { id = 346 points = 1 } # Huelva
province = { id = 347 points = 2 } # Seville
province = { id = 348 points = 7 } # Gibraltar
province = { id = 349 points = 1 } # Málaga
province = { id = 352 points = 1 } # Murcia
province = { id = 354 points = 2 } # València
province = { id = 356 points = 1 } # Tarragona
province = { id = 357 points = 2 } # Barcelona
province = { id = 359 points = 7 } # Toulouse
province = { id = 364 points = 7 } # Marseille
province = { id = 368 points = 7 } # Genoa
province = { id = 370 points = 7 } # Milan
province = { id = 376 points = 10 } # Munich
province = { id = 377 points = 2 } # Innsbruck
province = { id = 378 points = 7 } # Venice
province = { id = 380 points = 1 } # Ljubljana
province = { id = 382 points = 1 } # Zagreb
province = { id = 384 points = 1 } # Split
province = { id = 386 points = 1 } # Sarajevo
province = { id = 390 points = 2 } # Tirana
province = { id = 401 points = 1 } # Athens
province = { id = 409 points = 3 } # Istanbul
province = { id = 411 points = 1 } # Salonika
province = { id = 413 points = 1 } # Skopje
province = { id = 417 points = 1 } # Sofia
province = { id = 421 points = 1 } # Plovdiv
province = { id = 422 points = 1 } # Varna
province = { id = 424 points = 4 } # Bucharest
province = { id = 428 points = 2 } # Cluj-Napoca
province = { id = 431 points = 2 } # Ploesti
province = { id = 437 points = 1 } # Izmir
province = { id = 439 points = 1 } # Izmit
province = { id = 445 points = 1 } # Gaziantep
province = { id = 448 points = 2 } # Ankara
province = { id = 450 points = 1 } # Trebizond
province = { id = 453 points = 2 } # Belgrade
province = { id = 456 points = 2 } # Pecs
province = { id = 457 points = 2 } # Budapest
province = { id = 460 points = 2 } # Graz
province = { id = 462 points = 2 } # Salzburg
province = { id = 463 points = 6 } # Vienna
province = { id = 469 points = 6 } # Prague
province = { id = 470 points = 1 } # Pilsen
province = { id = 476 points = 4 } # Bratislava
province = { id = 479 points = 2 } # Cracow
province = { id = 483 points = 2 } # Lodz
province = { id = 485 points = 4 } # Warsaw
province = { id = 490 points = 2 } # Kosice
province = { id = 497 points = 1 } # Debrecen
province = { id = 501 points = 2 } # Lvov
province = { id = 512 points = 5 } # Bologna
province = { id = 515 points = 15 } # Rome
province = { id = 521 points = 6 } # Naples
province = { id = 523 points = 5 } # Taranto
province = { id = 525 points = 5 } # Palermo
province = { id = 528 points = 2 } # Lyon
province = { id = 532 points = 1 } # Bern
province = { id = 533 points = 1 } # Zürich
province = { id = 539 points = 1 } # Managua
province = { id = 540 points = 1 } # San José
province = { id = 541 points = 1 } # Vancouver
province = { id = 547 points = 1 } # Unalaska Island
province = { id = 549 points = 1 } # Anchorage
province = { id = 569 points = 1 } # Winnipeg
province = { id = 585 points = 1 } # Montréal
province = { id = 588 points = 1 } # Ottawa
province = { id = 589 points = 1 } # Toronto
province = { id = 595 points = 1 } # Concord
province = { id = 600 points = 1 } # Boston
province = { id = 602 points = 1 } # New York
province = { id = 606 points = 1 } # Washington D.C.
province = { id = 608 points = 1 } # Philadelphia
province = { id = 613 points = 1 } # Buffalo
province = { id = 614 points = 1 } # Pittsburgh
province = { id = 615 points = 1 } # Cleveland
province = { id = 616 points = 1 } # Detroit
province = { id = 619 points = 1 } # Indianapolis
province = { id = 620 points = 1 } # Chicago
province = { id = 621 points = 1 } # Milwaukee
province = { id = 633 points = 1 } # Norfolk
province = { id = 640 points = 1 } # Louisville
province = { id = 642 points = 1 } # Nashville
province = { id = 644 points = 1 } # Charleston
province = { id = 645 points = 1 } # Columbia
province = { id = 647 points = 1 } # Macon
province = { id = 651 points = 1 } # Miami
province = { id = 654 points = 2 } # Havana
province = { id = 657 points = 1 } # Guantánamo
province = { id = 662 points = 1 } # Midway Island
province = { id = 663 points = 1 } # Pearl Harbour
province = { id = 667 points = 6 } # Buenos Aires
province = { id = 670 points = 1 } # Atlanta
province = { id = 675 points = 1 } # Jackson
province = { id = 676 points = 1 } # Mobile
province = { id = 680 points = 1 } # New Orleans
province = { id = 684 points = 1 } # Little Rock
province = { id = 688 points = 1 } # Springfield
province = { id = 689 points = 1 } # St. Louis
province = { id = 690 points = 1 } # Kansas City
province = { id = 692 points = 1 } # Des Moines
province = { id = 693 points = 1 } # Minneapolis
province = { id = 698 points = 1 } # Bismarck
province = { id = 707 points = 1 } # Denver
province = { id = 715 points = 1 } # Dallas
province = { id = 716 points = 1 } # Houston
province = { id = 717 points = 1 } # San Antonio
province = { id = 724 points = 1 } # Albuquerque
province = { id = 730 points = 1 } # Phoenix
province = { id = 733 points = 1 } # Salt Lake City
province = { id = 747 points = 1 } # Monterrey
province = { id = 752 points = 2 } # Mexico City
province = { id = 753 points = 1 } # Puebla
province = { id = 754 points = 1 } # Acapulco
province = { id = 755 points = 1 } # Villahermosa
province = { id = 757 points = 1 } # Guatemala
province = { id = 759 points = 1 } # San Salvador
province = { id = 760 points = 1 } # Tegucigalpa
province = { id = 761 points = 1 } # San Diego
province = { id = 762 points = 1 } # Los Angeles
province = { id = 764 points = 1 } # Sacramento
province = { id = 765 points = 1 } # San Francisco
province = { id = 771 points = 1 } # Boise
province = { id = 774 points = 1 } # Great Falls
province = { id = 779 points = 1 } # Spokane
province = { id = 780 points = 1 } # Seattle
province = { id = 783 points = 1 } # Portland
province = { id = 787 points = 1 } # Rapid City
province = { id = 789 points = 1 } # Omaha
province = { id = 793 points = 1 } # Tulsa
province = { id = 803 points = 2 } # Barranquilla
province = { id = 804 points = 2 } # Maracaibo
province = { id = 811 points = 2 } # Caracas
province = { id = 812 points = 2 } # Cúcuta
province = { id = 813 points = 2 } # Bogotá
province = { id = 815 points = 2 } # Quito
province = { id = 830 points = 2 } # Lima
province = { id = 831 points = 2 } # Arequipa
province = { id = 832 points = 2 } # La Paz
province = { id = 837 points = 1 } # Asunción
province = { id = 839 points = 2 } # Antofagasta
province = { id = 840 points = 2 } # Santiago
province = { id = 843 points = 1 } # San Miguel de Tucumán
province = { id = 844 points = 2 } # Corrientes
province = { id = 845 points = 2 } # Córdoba
province = { id = 849 points = 1 } # Montevideo
province = { id = 852 points = 2 } # Mar del Plata
province = { id = 864 points = 1 } # Punta Arenas
province = { id = 875 points = 2 } # Cayenne
province = { id = 879 points = 2 } # Belém
province = { id = 881 points = 2 } # Recife
province = { id = 882 points = 2 } # Salvador
province = { id = 883 points = 3 } # Goiás
province = { id = 884 points = 2 } # Vitória
province = { id = 885 points = 2 } # Rio de Janeiro
province = { id = 886 points = 2 } # São Paulo
province = { id = 888 points = 1 } # Panamá
province = { id = 889 points = 5 } # Colon
province = { id = 892 points = 1 } # Port-au-Prince
province = { id = 893 points = 4 } # Santiago
province = { id = 894 points = 1 } # Santo Domingo
province = { id = 900 points = 5 } # Suez
province = { id = 901 points = 5 } # Port Said
province = { id = 903 points = 2 } # Cairo
province = { id = 906 points = 5 } # Alexandria
province = { id = 919 points = 3 } # Tobruk
province = { id = 924 points = 1 } # Bengazi
province = { id = 932 points = 3 } # Tripoli
province = { id = 939 points = 5 } # Tunis
province = { id = 949 points = 5 } # Algiers
province = { id = 957 points = 0 } # Ceuta
province = { id = 958 points = 2 } # Casablanca
province = { id = 981 points = 5 } # Dakar
province = { id = 992 points = 1 } # Monrovia
province = { id = 1046 points = 2 } # Addis Ababa
province = { id = 1092 points = 2 } # Libreville
province = { id = 1095 points = 1 } # Banana
province = { id = 1096 points = 1 } # Loanda
province = { id = 1100 points = 5 } # Nova Lisboa
province = { id = 1116 points = 3 } # Cape Town
province = { id = 1117 points = 2 } # Port Elisabeth
province = { id = 1119 points = 2 } # Durban
province = { id = 1120 points = 3 } # Johannesburg
province = { id = 1122 points = 1 } # Lourenço Marques
province = { id = 1127 points = 1 } # Élisabethville
province = { id = 1142 points = 1 } # Léopoldville
province = { id = 1146 points = 1 } # Cap Verde Islands
province = { id = 1163 points = 1 } # Yakutsk
province = { id = 1176 points = 1 } # Toyohara
province = { id = 1178 points = 1 } # Asahikawa
province = { id = 1179 points = 2 } # Sapporo
province = { id = 1180 points = 5 } # Sendai
province = { id = 1181 points = 5 } # Akita
province = { id = 1182 points = 5 } # Fukushima
province = { id = 1183 points = 5 } # Niigata
province = { id = 1184 points = 10 } # Tokyo
province = { id = 1185 points = 10 } # Nagoya
province = { id = 1186 points = 5 } # Kanazawa
province = { id = 1187 points = 10 } # Osaka
province = { id = 1189 points = 5 } # Shikoku
province = { id = 1190 points = 5 } # Fukuoka
province = { id = 1191 points = 5 } # Kagoshima
province = { id = 1193 points = 2 } # Okinawa
province = { id = 1196 points = 1 } # Busan
province = { id = 1199 points = 1 } # Seoul
province = { id = 1201 points = 1 } # Pyongyang
province = { id = 1204 points = 1 } # Tianjin
province = { id = 1205 points = 5 } # Beiping
province = { id = 1207 points = 1 } # Jining
province = { id = 1210 points = 1 } # Baoding
province = { id = 1214 points = 1 } # Yantai
province = { id = 1216 points = 1 } # Jinan
province = { id = 1221 points = 1 } # Hefei
province = { id = 1225 points = 2 } # Taiyuan
province = { id = 1227 points = 1 } # Luoyang
province = { id = 1229 points = 1 } # Nanyang
province = { id = 1232 points = 1 } # Hankou
province = { id = 1234 points = 1 } # Wuhu
province = { id = 1235 points = 3 } # Nanjing
province = { id = 1237 points = 2 } # Shanghai
province = { id = 1238 points = 1 } # Hangzhou
province = { id = 1250 points = 1 } # Ganzhou
province = { id = 1253 points = 1 } # Wuchang
province = { id = 1257 points = 1 } # Hengyang
province = { id = 1258 points = 1 } # Guilin
province = { id = 1261 points = 1 } # Huaihua
province = { id = 1268 points = 1 } # Nancheng
province = { id = 1270 points = 1 } # Xianyang
province = { id = 1271 points = 1 } # Yan'an
province = { id = 1272 points = 1 } # Yuling
province = { id = 1277 points = 1 } # Tianshui
province = { id = 1280 points = 3 } # Chongqing
province = { id = 1281 points = 1 } # Ya'an
province = { id = 1282 points = 1 } # Kangding
province = { id = 1291 points = 1 } # Myitkyina
province = { id = 1293 points = 1 } # Xiaguan
province = { id = 1294 points = 1 } # Baoshan
province = { id = 1295 points = 1 } # Lashio
province = { id = 1296 points = 1 } # Mandalay
province = { id = 1299 points = 2 } # Rangoon
province = { id = 1307 points = 3 } # Kunming
province = { id = 1309 points = 1 } # Bose
province = { id = 1310 points = 1 } # Liuzhou
province = { id = 1313 points = 2 } # Guangzhou
province = { id = 1315 points = 2 } # Hong Kong
province = { id = 1316 points = 1 } # Macao
province = { id = 1321 points = 1 } # Hainan
province = { id = 1323 points = 10 } # Taipei
province = { id = 1328 points = 5 } # Hanoi
province = { id = 1331 points = 1 } # Khon Kaen
province = { id = 1337 points = 10 } # Saigon
province = { id = 1343 points = 3 } # Bangkok
province = { id = 1345 points = 1 } # Thom Buri
province = { id = 1348 points = 1 } # Singora
province = { id = 1350 points = 2 } # Kota Bahru
province = { id = 1352 points = 1 } # Kuala Lumpur
province = { id = 1353 points = 3 } # Singapore
province = { id = 1355 points = 2 } # Medan
province = { id = 1358 points = 2 } # Palembang
province = { id = 1359 points = 2 } # Oosthaven
province = { id = 1360 points = 1 } # Chengdu
province = { id = 1363 points = 1 } # Anshun
province = { id = 1364 points = 1 } # Guiyang
province = { id = 1371 points = 3 } # Tetyukhe
province = { id = 1372 points = 10 } # Vladivostok
province = { id = 1373 points = 1 } # Spassk-Dalnij
province = { id = 1379 points = 4 } # Harbin
province = { id = 1389 points = 2 } # Mukden
province = { id = 1397 points = 2 } # Changde
province = { id = 1404 points = 1 } # Ulan Bator
province = { id = 1420 points = 1 } # Khobdo
province = { id = 1422 points = 1 } # Alma-Ata
province = { id = 1427 points = 1 } # Tashkent
province = { id = 1433 points = 1 } # Urumqi
province = { id = 1442 points = 1 } # Golmud
province = { id = 1443 points = 1 } # Xining
province = { id = 1453 points = 2 } # Lhasa
province = { id = 1455 points = 1 } # Punakha
province = { id = 1457 points = 5 } # Calcutta
province = { id = 1469 points = 5 } # Delhi
province = { id = 1473 points = 1 } # Kathmandu
province = { id = 1486 points = 1 } # Kabul
province = { id = 1492 points = 1 } # Herat
province = { id = 1497 points = 1 } # Bandar Abbas
province = { id = 1498 points = 1 } # Babolsar
province = { id = 1502 points = 2 } # Teheran
province = { id = 1505 points = 5 } # Bombay
province = { id = 1525 points = 1 } # Okhotsk
province = { id = 1535 points = 3 } # Angutikha
province = { id = 1548 points = 1 } # Novosibirsk
province = { id = 1552 points = 1 } # Omsk
province = { id = 1599 points = 1 } # Iwo Jima
province = { id = 1601 points = 1 } # Eniwetok
province = { id = 1608 points = 1 } # Kwajalein
province = { id = 1611 points = 1 } # Nauru
province = { id = 1613 points = 2 } # Truk
province = { id = 1618 points = 1 } # Ulithi
province = { id = 1619 points = 1 } # Yap
province = { id = 1621 points = 1 } # Palau
province = { id = 1624 points = 2 } # Guam
province = { id = 1626 points = 2 } # Tinian
province = { id = 1627 points = 2 } # Saipan
province = { id = 1628 points = 3 } # Batavia
province = { id = 1640 points = 2 } # Makassar
province = { id = 1650 points = 2 } # Balikpapan
province = { id = 1665 points = 2 } # Hollandia
province = { id = 1670 points = 1 } # Rabaul
province = { id = 1672 points = 1 } # Lae
province = { id = 1679 points = 2 } # Port Moresby
province = { id = 1682 points = 1 } # Bougainville
province = { id = 1685 points = 2 } # Guadalcanal
province = { id = 1692 points = 1 } # Noumea
province = { id = 1696 points = 1 } # Townsville
province = { id = 1703 points = 2 } # Darwin
province = { id = 1712 points = 1 } # Perth
province = { id = 1722 points = 2 } # Brisbane
province = { id = 1724 points = 1 } # Newcastle
province = { id = 1727 points = 3 } # Sydney
province = { id = 1728 points = 2 } # Canberra
province = { id = 1730 points = 2 } # Melbourne
province = { id = 1733 points = 1 } # Adelaide
province = { id = 1736 points = 1 } # Mindoro
province = { id = 1737 points = 3 } # Manila
province = { id = 1738 points = 1 } # Bataan
province = { id = 1739 points = 1 } # Clark Field
province = { id = 1745 points = 1 } # Leyte
province = { id = 1749 points = 1 } # Cagayan
province = { id = 1750 points = 1 } # Davao
province = { id = 1752 points = 1 } # Fiji
province = { id = 1756 points = 1 } # Samoa
province = { id = 1769 points = 1 } # Tarawa
province = { id = 1786 points = 1 } # Wake Island
province = { id = 1792 points = 5 } # Damascus
province = { id = 1797 points = 1 } # Jerusalem
province = { id = 1807 points = 1 } # Riyadh
province = { id = 1819 points = 2 } # Mascate
province = { id = 1823 points = 1 } # Basrah
province = { id = 1825 points = 1 } # Abadan
province = { id = 1826 points = 1 } # Esfahan
province = { id = 1844 points = 2 } # Maikop
province = { id = 1859 points = 1 } # Tabriz
province = { id = 1864 points = 2 } # Mosul
province = { id = 1866 points = 3 } # Baghdad
province = { id = 1867 points = 1 } # The Azores
province = { id = 1868 points = 1 } # Auckland
province = { id = 1871 points = 1 } # Wellington
province = { id = 1872 points = 1 } # Christchurch
province = { id = 130 points = 1 }
province = { id = 137 points = 1 }
province = { id = 147 points = 1 }
province = { id = 139 points = 1 }
province = { id = 199 points = 1 }
province = { id = 202 points = 1 }
province = { id = 205 points = 1 }
province = { id = 2606 points = 1 }
province = { id = 206 points = 1 }
province = { id = 510 points = 1 }
province = { id = 1811 points = 1 }
province = { id = 214 points = 1 }
province = { id = 503 points = 1 }
province = { id = 502 points = 1 }
province = { id = 487 points = 1 }
province = { id = 486 points = 1 }
province = { id = 481 points = 1 }
province = { id = 306 points = 1 }
province = { id = 208 points = 1 }
province = { id = 505 points = 1 }
province = { id = 1595 points = 1 }
province = { id = 473 points = 1 }
province = { id = 302 points = 1 }
province = { id = 475 points = 1 }
province = { id = 499 points = 1 }
province = { id = 1887 points = 1 }
province = { id = 225 points = 1 }
province = { id = 274 points = 1 }
province = { id = 161 points = 1 }
province = { id = 260 points = 1 }
province = { id = 269 points = 1 }
province = { id = 1830 points = 1 }
province = { id = 279 points = 1 }
province = { id = 1780 points = 1 }
province = { id = 281 points = 1 }
province = { id = 255 points = 1 }
province = { id = 1838 points = 1 }
province = { id = 1850 points = 1 }
province = { id = 1856 points = 1 }
province = { id = 1907 points = 1 }
province = { id = 1847 points = 1 }
province = { id = 1854 points = 1 }
province = { id = 408 points = 1 }
province = { id = 392 points = 1 }
province = { id = 444 points = 1 }
province = { id = 415 points = 1 }
province = { id = 389 points = 1 }
province = { id = 388 points = 1 }
province = { id = 385 points = 1 }
province = { id = 451 points = 1 }
province = { id = 454 points = 1 }
province = { id = 1173 points = 1 }
province = { id = 434 points = 1 }
province = { id = 433 points = 1 }
province = { id = 436 points = 1 }
province = { id = 495 points = 1 }
province = { id = 426 points = 1 }
province = { id = 420 points = 1 }
province = { id = 395 points = 1 }
province = { id = 526 points = 1 }
province = { id = 524 points = 1 }
province = { id = 543 points = 1 }
province = { id = 513 points = 1 }
province = { id = 531 points = 1 }
province = { id = 666 points = 1 }
province = { id = 530 points = 1 }
province = { id = 3217 points = 1 }
province = { id = 315 points = 1 }
province = { id = 74 points = 1 }
province = { id = 313 points = 1 }
province = { id = 87 points = 1 }
province = { id = 309 points = 1 }
province = { id = 296 points = 1 }
province = { id = 46 points = 1 }
province = { id = 49 points = 1 }
province = { id = 79 points = 1 }
province = { id = 68 points = 1 }
province = { id = 121 points = 1 }
province = { id = 127 points = 1 }
province = { id = 2276 points = 5 }
province = { id = 118 points = 1 }
province = { id = 129 points = 1 }
province = { id = 109 points = 1 }
province = { id = 8 points = 1 }
province = { id = 1166 points = 1 }
province = { id = 7 points = 1 }
province = { id = 5 points = 1 }
province = { id = 25 points = 1 }
province = { id = 26 points = 1 }
province = { id = 1 points = 1 }
province = { id = 15 points = 1 }
province = { id = 12 points = 1 }
province = { id = 3038 points = 1 }
province = { id = 14 points = 1 }
province = { id = 23 points = 1 }
province = { id = 21 points = 1 }
province = { id = 13 points = 1 }
province = { id = 17 points = 1 }
province = { id = 34 points = 1 }
province = { id = 33 points = 1 }
province = { id = 35 points = 1 }
province = { id = 59 points = 1 }
province = { id = 62 points = 1 }
province = { id = 841 points = 1 }
province = { id = 2557 points = 1 }
province = { id = 529 points = 1 }
province = { id = 360 points = 1 }
province = { id = 2509 points = 1 }
province = { id = 366 points = 1 }
province = { id = 362 points = 1 }
province = { id = 3060 points = 1 }
province = { id = 2583 points = 1 }
province = { id = 2273 points = 1 }
province = { id = 2581 points = 1 }
province = { id = 534 points = 1 }
province = { id = 2300 points = 1 }
province = { id = 2457 points = 1 }
province = { id = 332 points = 1 }
province = { id = 1726 points = 1 }
province = { id = 2244 points = 1 }
province = { id = 1532 points = 1 }
province = { id = 343 points = 1 }
province = { id = 1531 points = 1 }
province = { id = 330 points = 1 }
province = { id = 351 points = 1 }
province = { id = 350 points = 1 }
province = { id = 337 points = 1 }
province = { id = 966 points = 1 }
province = { id = 950 points = 1 }
province = { id = 936 points = 1 }
province = { id = 942 points = 1 }
province = { id = 910 points = 1 }
province = { id = 907 points = 1 }
province = { id = 1025 points = 1 }
province = { id = 1798 points = 1 }
province = { id = 1794 points = 1 }
province = { id = 1862 points = 1 }
province = { id = 1865 points = 1 }
province = { id = 1804 points = 1 }
province = { id = 1809 points = 1 }
province = { id = 1812 points = 1 }
province = { id = 1813 points = 1 }
province = { id = 1481 points = 1 }
province = { id = 1490 points = 1 }
province = { id = 1429 points = 1 }
province = { id = 2853 points = 1 }
province = { id = 700 points = 1 }
province = { id = 1500 points = 1 }
province = { id = 1488 points = 1 }
province = { id = 1424 points = 1 }
province = { id = 1475 points = 1 }
province = { id = 1482 points = 1 }
province = { id = 1493 points = 1 }
province = { id = 1485 points = 1 }
province = { id = 1581 points = 1 }
province = { id = 1569 points = 1 }
province = { id = 1570 points = 1 }
province = { id = 993 points = 1 }
province = { id = 995 points = 1 }
province = { id = 1002 points = 1 }
province = { id = 994 points = 1 }
province = { id = 973 points = 1 }
province = { id = 1003 points = 1 }
province = { id = 997 points = 1 }
province = { id = 1084 points = 1 }
province = { id = 1008 points = 1 }
province = { id = 1007 points = 1 }
province = { id = 2764 points = 1 }
province = { id = 1080 points = 1 }
province = { id = 1066 points = 1 }
province = { id = 1030 points = 1 }
province = { id = 1056 points = 1 }
province = { id = 1060 points = 1 }
province = { id = 1064 points = 1 }
province = { id = 1071 points = 1 }
province = { id = 1075 points = 1 }
province = { id = 1140 points = 1 }
province = { id = 1129 points = 1 }
province = { id = 2790 points = 1 }
province = { id = 1134 points = 1 }
province = { id = 1125 points = 1 }
province = { id = 1112 points = 1 }
province = { id = 2643 points = 1 }
province = { id = 1110 points = 1 }
province = { id = 1118 points = 1 }
province = { id = 1114 points = 1 }
province = { id = 851 points = 1 }
province = { id = 860 points = 1 }
province = { id = 856 points = 1 }
province = { id = 846 points = 1 }
province = { id = 848 points = 1 }
province = { id = 847 points = 1 }
province = { id = 887 points = 1 }
province = { id = 826 points = 1 }
province = { id = 877 points = 1 }
province = { id = 872 points = 1 }
province = { id = 873 points = 1 }
province = { id = 870 points = 1 }
province = { id = 868 points = 1 }
province = { id = 890 points = 1 }
province = { id = 814 points = 1 }
province = { id = 818 points = 1 }
province = { id = 816 points = 1 }
province = { id = 829 points = 1 }
province = { id = 838 points = 1 }
province = { id = 854 points = 1 }
province = { id = 2655 points = 1 }
province = { id = 891 points = 1 }
province = { id = 737 points = 1 }
province = { id = 740 points = 1 }
province = { id = 745 points = 1 }
province = { id = 738 points = 1 }
province = { id = 734 points = 1 }
province = { id = 776 points = 1 }
province = { id = 2677 points = 1 }
province = { id = 2367 points = 1 }
province = { id = 792 points = 1 }
province = { id = 678 points = 1 }
province = { id = 624 points = 1 }
province = { id = 2261 points = 1 }
province = { id = 627 points = 1 }
province = { id = 650 points = 1 }
province = { id = 637 points = 1 }
province = { id = 629 points = 1 }
province = { id = 607 points = 1 }
province = { id = 603 points = 1 }
province = { id = 612 points = 1 }
province = { id = 574 points = 1 }
province = { id = 796 points = 1 }
province = { id = 797 points = 1 }
province = { id = 1723 points = 1 }
province = { id = 1711 points = 1 }
province = { id = 1718 points = 1 }
province = { id = 1677 points = 1 }
province = { id = 1622 points = 1 }
province = { id = 1646 points = 1 }
province = { id = 1631 points = 1 }
province = { id = 1339 points = 1 }
province = { id = 1341 points = 1 }
province = { id = 1333 points = 1 }
province = { id = 1335 points = 1 }
province = { id = 1332 points = 1 }
province = { id = 1329 points = 1 }
province = { id = 2950 points = 1 }
province = { id = 1326 points = 1 }
province = { id = 1286 points = 1 }
province = { id = 2641 points = 1 }
province = { id = 1507 points = 1 }
province = { id = 1517 points = 1 }
province = { id = 722 points = 1 }
province = { id = 1458 points = 1 }
province = { id = 1514 points = 1 }
province = { id = 1694 points = 1 }
province = { id = 1466 points = 1 }
province = { id = 1474 points = 1 }
province = { id = 1452 points = 1 }
province = { id = 1202 points = 1 }
province = { id = 1197 points = 1 }
province = { id = 1195 points = 1 }
province = { id = 2226 points = 1 }
province = { id = 3099 points = 1 }
province = { id = 1200 points = 1 }
province = { id = 1376 points = 1 }
province = { id = 1392 points = 1 }
province = { id = 2231 points = 1 }
province = { id = 1393 points = 1 }
province = { id = 2340 points = 1 }
province = { id = 1247 points = 1 }
province = { id = 2569 points = 1 }
province = { id = 2551 points = 1 }
province = { id = 235 points = 1 }
province = { id = 322 points = 1 }
province = { id = 135 points = 1 }
province = { id = 152 points = 1 }
province = { id = 1188 points = 1 }
province = { id = 1174 points = 1 }
province = { id = 1528 points = 1 }
province = { id = 1078 points = 1 }
province = { id = 959 points = 1 }
province = { id = 254 points = 1 }
province = { id = 82 points = 1 }
province = { id = 76 points = 1 }
province = { id = 2611 points = 1 }
province = { id = 1414 points = 1 }
province = { id = 1520 points = 1 }
province = { id = 1522 points = 1 }
province = { id = 1167 points = 1 }
province = { id = 1382 points = 1 }
province = { id = 1431 points = 1 }
province = { id = 785 points = 1 }
province = { id = 1483 points = 1 }
province = { id = 2831 points = 1 }
province = { id = 1832 points = 1 }
province = { id = 166 points = 1 }
province = { id = 201 points = 1 }
province = { id = 458 points = 1 }
province = { id = 2447 points = 1 }
province = { id = 493 points = 1 }
province = { id = 1248 points = 1 }
province = { id = 1325 points = 1 }
province = { id = 2523 points = 1 }
province = { id = 2517 points = 1 }
province = { id = 2241 points = 1 }
province = { id = 2504 points = 1 }
province = { id = 3741 points = 1 }
province = { id = 1223 points = 1 }
province = { id = 1796 points = 1 }
province = { id = 553 points = 1 }
province = { id = 552 points = 1 }
province = { id = 558 points = 1 }
province = { id = 6837 points = 1 }
province = { id = 576 points = 1 }
province = { id = 578 points = 1 }
province = { id = 579 points = 1 }
province = { id = 580 points = 1 }
province = { id = 571 points = 1 }
province = { id = 799 points = 1 }
province = { id = 798 points = 1 }
province = { id = 556 points = 1 }
province = { id = 2365 points = 1 }
province = { id = 6110 points = 1 }
province = { id = 770 points = 1 }
province = { id = 705 points = 1 }
province = { id = 768 points = 1 }
province = { id = 6159 points = 1 }
province = { id = 709 points = 1 }
province = { id = 728 points = 1 }
province = { id = 725 points = 1 }
province = { id = 727 points = 1 }
province = { id = 721 points = 1 }
province = { id = 719 points = 1 }
province = { id = 718 points = 1 }
province = { id = 6255 points = 1 }
province = { id = 686 points = 1 }
province = { id = 2682 points = 1 }
province = { id = 6231 points = 1 }
province = { id = 2680 points = 1 }
province = { id = 790 points = 1 }
province = { id = 6305 points = 1 }
province = { id = 699 points = 1 }
province = { id = 694 points = 1 }
province = { id = 6408 points = 1 }
province = { id = 622 points = 1 }
province = { id = 6352 points = 1 }
province = { id = 683 points = 1 }
province = { id = 679 points = 1 }
province = { id = 6274 points = 1 }
province = { id = 2692 points = 1 }
province = { id = 672 points = 1 }
province = { id = 646 points = 1 }
province = { id = 677 points = 1 }
province = { id = 636 points = 1 }
province = { id = 671 points = 1 }
province = { id = 639 points = 1 }
province = { id = 6473 points = 1 }
province = { id = 6460 points = 1 }
province = { id = 626 points = 1 }
province = { id = 628 points = 1 }
province = { id = 2721 points = 1 }
province = { id = 604 points = 1 }
province = { id = 605 points = 1 }
province = { id = 6463 points = 1 }
province = { id = 598 points = 1 }
province = { id = 2719 points = 1 }
province = { id = 601 points = 1 }
province = { id = 6374 points = 1 }
province = { id = 6367 points = 1 }
province = { id = 2693 points = 1 }
province = { id = 4353 points = 1 }
province = { id = 739 points = 1 }
province = { id = 2698 points = 1 }
province = { id = 743 points = 1 }
province = { id = 2695 points = 1 }
province = { id = 4369 points = 1 }
province = { id = 742 points = 1 }
province = { id = 7348 points = 1 }
province = { id = 2694 points = 1 }
province = { id = 2699 points = 1 }
province = { id = 2697 points = 1 }
province = { id = 2701 points = 1 }
province = { id = 744 points = 1 }
province = { id = 751 points = 1 }
province = { id = 4330 points = 1 }
province = { id = 741 points = 1 }
province = { id = 749 points = 1 }
province = { id = 756 points = 1 }
province = { id = 4310 points = 1 }
province = { id = 822 points = 1 }
province = { id = 2737 points = 1 }
province = { id = 2992 points = 1 }
province = { id = 2027 points = 1 }
province = { id = 869 points = 1 }
province = { id = 874 points = 1 }
province = { id = 802 points = 1 }
province = { id = 2740 points = 1 }
province = { id = 876 points = 1 }
province = { id = 880 points = 1 }
province = { id = 2666 points = 1 }
province = { id = 2671 points = 1 }
province = { id = 2662 points = 1 }
province = { id = 2665 points = 1 }
province = { id = 878 points = 1 }
province = { id = 2664 points = 1 }
province = { id = 4093 points = 1 }
province = { id = 824 points = 1 }
province = { id = 834 points = 1 }
province = { id = 835 points = 1 }
province = { id = 2668 points = 1 }
province = { id = 2667 points = 1 }
province = { id = 2320 points = 1 }
province = { id = 2672 points = 1 }
province = { id = 2659 points = 1 }
province = { id = 4055 points = 1 }
province = { id = 833 points = 1 }
province = { id = 853 points = 1 }
province = { id = 857 points = 1 }
province = { id = 1943 points = 1 }
province = { id = 862 points = 1 }
province = { id = 982 points = 1 }
province = { id = 983 points = 1 }
province = { id = 987 points = 1 }
province = { id = 988 points = 1 }
province = { id = 978 points = 1 }
province = { id = 977 points = 1 }
province = { id = 991 points = 1 }
province = { id = 986 points = 1 }
province = { id = 4483 points = 1 }
province = { id = 2763 points = 1 }
province = { id = 1000 points = 1 }
province = { id = 4505 points = 1 }
province = { id = 4580 points = 1 }
province = { id = 1085 points = 1 }
province = { id = 2766 points = 1 }
province = { id = 1010 points = 1 }
province = { id = 1011 points = 1 }
province = { id = 1009 points = 1 }
province = { id = 1145 points = 1 }
province = { id = 4794 points = 1 }
province = { id = 1086 points = 1 }
province = { id = 1089 points = 1 }
province = { id = 2745 points = 1 }
province = { id = 929 points = 1 }
province = { id = 1093 points = 1 }
province = { id = 2750 points = 1 }
province = { id = 1098 points = 1 }
province = { id = 4817 points = 1 }
province = { id = 1074 points = 1 }
province = { id = 2760 points = 1 }
province = { id = 2758 points = 1 }
province = { id = 1073 points = 1 }
province = { id = 2756 points = 1 }
province = { id = 2754 points = 1 }
province = { id = 1144 points = 1 }
province = { id = 1102 points = 1 }
province = { id = 1099 points = 1 }
province = { id = 2809 points = 1 }
province = { id = 1111 points = 1 }
province = { id = 1124 points = 1 }
province = { id = 1133 points = 1 }
province = { id = 1113 points = 1 }
province = { id = 2644 points = 1 }
province = { id = 975 points = 1 }
province = { id = 5015 points = 1 }
province = { id = 1115 points = 1 }
province = { id = 5017 points = 1 }
province = { id = 5052 points = 1 }
province = { id = 2775 points = 1 }
province = { id = 2778 points = 1 }
province = { id = 4745 points = 1 }
province = { id = 1062 points = 1 }
province = { id = 2283 points = 1 }
province = { id = 1063 points = 1 }
province = { id = 1061 points = 1 }
province = { id = 2813 points = 1 }
province = { id = 2284 points = 1 }
province = { id = 4720 points = 1 }
province = { id = 1035 points = 1 }
province = { id = 2635 points = 1 }
province = { id = 1058 points = 1 }
province = { id = 1037 points = 1 }
province = { id = 1050 points = 1 }
province = { id = 1039 points = 1 }
province = { id = 1043 points = 1 }
province = { id = 1045 points = 1 }
province = { id = 1065 points = 1 }
province = { id = 4758 points = 1 }
province = { id = 2814 points = 1 }
province = { id = 1067 points = 1 }
province = { id = 4 points = 1 }
province = { id = 4188 points = 1 }
province = { id = 4196 points = 1 }
province = { id = 1808 points = 1 }
province = { id = 2019 points = 1 }
province = { id = 2496 points = 1 }
province = { id = 4154 points = 1 }
province = { id = 1822 points = 1 }
province = { id = 2878 points = 1 }
province = { id = 446 points = 1 }
province = { id = 1855 points = 1 }
province = { id = 1863 points = 1 }
province = { id = 1793 points = 1 }
province = { id = 438 points = 1 }
province = { id = 2613 points = 1 }
province = { id = 442 points = 1 }
province = { id = 449 points = 1 }
province = { id = 2879 points = 1 }
province = { id = 1852 points = 1 }
province = { id = 2880 points = 1 }
province = { id = 396 points = 1 }
province = { id = 412 points = 1 }
province = { id = 391 points = 1 }
province = { id = 387 points = 1 }
province = { id = 383 points = 1 }
province = { id = 2325 points = 1 }
province = { id = 369 points = 1 }
province = { id = 3235 points = 1 }
province = { id = 471 points = 1 }
province = { id = 7261 points = 1 }
province = { id = 3382 points = 1 }
province = { id = 1152 points = 1 }
province = { id = 256 points = 1 }
province = { id = 1858 points = 1 }
province = { id = 1845 points = 1 }
province = { id = 1849 points = 1 }
province = { id = 3435 points = 1 }
province = { id = 1857 points = 1 }
province = { id = 282 points = 1 }
province = { id = 247 points = 1 }
province = { id = 1568 points = 1 }
province = { id = 2240 points = 1 }
province = { id = 1597 points = 1 }
province = { id = 1598 points = 1 }
province = { id = 276 points = 1 }
province = { id = 284 points = 1 }
province = { id = 178 points = 1 }
province = { id = 177 points = 1 }
province = { id = 200 points = 1 }
province = { id = 171 points = 1 }
province = { id = 156 points = 1 }
province = { id = 1831 points = 1 }
province = { id = 1777 points = 1 }
province = { id = 158 points = 1 }
province = { id = 1774 points = 1 }
province = { id = 1841 points = 1 }
province = { id = 1151 points = 1 }
province = { id = 1842 points = 1 }
province = { id = 1567 points = 1 }
province = { id = 1828 points = 1 }
province = { id = 3667 points = 1 }
province = { id = 3686 points = 1 }
province = { id = 1773 points = 1 }
province = { id = 1575 points = 1 }
province = { id = 1572 points = 1 }
province = { id = 1573 points = 1 }
province = { id = 1557 points = 1 }
province = { id = 3474 points = 1 }
province = { id = 1587 points = 1 }
province = { id = 1550 points = 1 }
province = { id = 1543 points = 1 }
province = { id = 1540 points = 1 }
province = { id = 7000 points = 1 }
province = { id = 1545 points = 1 }
province = { id = 1539 points = 1 }
province = { id = 1561 points = 1 }
province = { id = 1418 points = 1 }
province = { id = 1562 points = 1 }
province = { id = 1413 points = 1 }
province = { id = 1417 points = 1 }
province = { id = 3575 points = 1 }
province = { id = 3551 points = 1 }
province = { id = 1411 points = 1 }
province = { id = 1523 points = 1 }
province = { id = 1527 points = 1 }
province = { id = 1366 points = 1 }
province = { id = 1172 points = 1 }
province = { id = 1171 points = 1 }
province = { id = 1447 points = 1 }
province = { id = 1441 points = 1 }
province = { id = 2533 points = 1 }
province = { id = 2529 points = 1 }
province = { id = 1244 points = 1 }
province = { id = 2826 points = 1 }
province = { id = 687 points = 1 }
province = { id = 1468 points = 1 }
province = { id = 1465 points = 1 }
province = { id = 1464 points = 1 }
province = { id = 1467 points = 1 }
province = { id = 1506 points = 1 }
province = { id = 775 points = 1 }
province = { id = 5275 points = 1 }
province = { id = 5197 points = 1 }
province = { id = 2642 points = 1 }
province = { id = 2824 points = 1 }
province = { id = 1642 points = 1 }
province = { id = 1357 points = 1 }
province = { id = 1661 points = 1 }
province = { id = 1632 points = 1 }
province = { id = 5749 points = 1 }
province = { id = 1651 points = 1 }
province = { id = 1653 points = 1 }
province = { id = 1647 points = 1 }
province = { id = 1742 points = 1 }
province = { id = 1748 points = 1 }
province = { id = 5717 points = 1 }
province = { id = 1322 points = 1 }
province = { id = 1656 points = 1 }
province = { id = 1659 points = 1 }
province = { id = 5967 points = 1 }
province = { id = 1707 points = 1 }
province = { id = 1704 points = 1 }
province = { id = 1717 points = 1 }
province = { id = 1732 points = 1 }
province = { id = 2976 points = 1 }
province = { id = 1729 points = 1 }
province = { id = 1715 points = 1 }
province = { id = 1698 points = 1 }
province = { id = 2989 points = 1 }
province = { id = 1693 points = 1 }
province = { id = 1873 points = 1 }
province = { id = 6061 points = 1 }
province = { id = 1609 points = 1 }
province = { id = 1688 points = 1 }
province = { id = 7242 points = 1 }
province = { id = 680 points = 1 }
province = { id = 681 points = 1 }
province = { id = 704 points = 1 }
province = { id = 758 points = 1 }
province = { id = 2049 points = 1 }
province = { id = 3825 points = 1 }
province = { id = 821 points = 1 }
province = { id = 3800 points = 1 }
province = { id = 2927 points = 1 }
province = { id = 810 points = 1 }
province = { id = 2658 points = 1 }
province = { id = 3843 points = 1 }
province = { id = 827 points = 1 }
province = { id = 3856 points = 1 }
province = { id = 836 points = 1 }
province = { id = 3817 points = 1 }
province = { id = 855 points = 1 }
province = { id = 2490 points = 1 }
province = { id = 850 points = 1 }
province = { id = 2654 points = 1 }
province = { id = 2991 points = 1 }
province = { id = 858 points = 1 }
province = { id = 825 points = 1 }
province = { id = 4008 points = 1 }
province = { id = 116 points = 1 }
province = { id = 1162 points = 1 }
province = { id = 2866 points = 1 }
province = { id = 5344 points = 1 }
province = { id = 1480 points = 1 }
province = { id = 3127 points = 1 }
province = { id = 1658 points = 1 }
province = { id = 1635 points = 1 }
province = { id = 2937 points = 1 }
province = { id = 2981 points = 1 }
province = { id = 1725 points = 1 }
province = { id = 2979 points = 1 }
province = { id = 2985 points = 1 }
province = { id = 2978 points = 1 }
province = { id = 6022 points = 1 }
province = { id = 2988 points = 1 }
province = { id = 6009 points = 1 }
province = { id = 1708 points = 1 }
province = { id = 1709 points = 1 }
province = { id = 1713 points = 1 }
province = { id = 2966 points = 1 }
province = { id = 5988 points = 1 }
province = { id = 3879 points = 1 }
province = { id = 842 points = 1 }
province = { id = 2728 points = 1 }
province = { id = 6712 points = 1 }
province = { id = 6738 points = 1 }
province = { id = 6803 points = 1 }
province = { id = 6753 points = 1 }
province = { id = 2726 points = 1 }
province = { id = 590 points = 1 }
province = { id = 2730 points = 1 }
province = { id = 2731 points = 1 }
province = { id = 2733 points = 1 }
province = { id = 1909 points = 1 }
province = { id = 2732 points = 1 }
province = { id = 2735 points = 1 }
province = { id = 2851 points = 1 }
province = { id = 1848 points = 1 }
province = { id = 1149 points = 1 }
province = { id = 2849 points = 1 }
province = { id = 2470 points = 1 }
province = { id = 2850 points = 1 }
province = { id = 2848 points = 1 }
province = { id = 1787 points = 1 }
province = { id = 1582 points = 1 }
province = { id = 3513 points = 1 }
province = { id = 1578 points = 1 }
province = { id = 3517 points = 1 }
province = { id = 1583 points = 1 }
province = { id = 1428 points = 1 }
province = { id = 1425 points = 1 }
province = { id = 1419 points = 1 }
province = { id = 2486 points = 1 }
province = { id = 1381 points = 1 }
province = { id = 1267 points = 1 }
province = { id = 5626 points = 1 }
